# Generated by Django 3.0.8 on 2020-07-24 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('hex', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=128)),
                ('model', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('transmission', models.SmallIntegerField()),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cars.Color')),
            ],
        ),
    ]
