# Generated by Django 3.0.8 on 2020-07-26 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.SmallIntegerField(choices=[(0, 'механика'), (1, 'автомат'), (2, 'робот')]),
        ),
    ]
